### ISSUE TITLE
How to add token?

### ISSUE THREAD

**Issue by unixversal** [pkumarat/Telegram_Bot#1]
How shall I add the token in the uipath activity? Adding it c&p in quotes displays an error String cannot be converted to System.Security.SecureString. Adding it without quotes displays error that the end is expected? Thx for a hint

**Comment by pkumarat** [comment]
> How shall I add the token in the uipath activity? Adding it c&p in quotes displays an error String cannot be converted to System.Security.SecureString. Adding it without quotes displays error that the end is expected? Thx for a hint

Hello Chris,
Sorry for the delayed response.

Since the Token Bot token is a secure credential the datatype for this variable is given as SecureString in the custom activity.

SecureString can be passed into Bot in below methods

Method 1. If you need to hard code the token for testing within the coding, you can create a variable with datatype as SecureString and pass the token as default value using the new NetworkCredential as shown in below example 
Example: 
Variable Name - Bot_Token
Variable Type - SecureString
Default value - new NetworkCredential(String.Empty, "<bot-token>").SecurePassword

Please note  Since you are passing value with new NetworkCredential, you must also have a variable created with variable type NetworkCredential.
-------------------------------------------------------------------------------------------
Method 2: The Bot token can be added as a windows credential and passed into the code via a JSON file.

--------------------------------------------------------------------------------------------

Method 3: The Bot token can be added into the Orchestrator as a credential asset and then passed into the code.

**Comment by pkumarat** [comment]
Default value - new NetworkCredential(String.Empty, "bot-token").SecurePassword

**Comment by unixversal** [comment]
Hi pkumarat,

I could solve the matter by adding a "missing activity" that was not included in my Version (15?) anymore. This way I could use a normal set secure pw method. THanks for the follow up anyways :)
